language: java
jdk:
- openjdk12
env:
  matrix:
  - DSTAMP=$(date +%F)
  global:
    ssecure: "Ncz+uoi+r4aQgeG9b+pbpVhffNZqSRROH//H8FfrZErEPYLQK0RBHjM9o/DgziOmW8hZ3rIFvGoAe8niS6cAGZEa1kCekiICweZQh4jdkJxPK0unvpd09b2ZNHx1FSTkGDHssZ74IvyAsFrpDXzUfR3FNDqAySd8Q46EbZNMic+mQlxLihhxjdUyZwbjUoBFr0U0JTV4P3jGEQGzBWNbZSjLnoDMeiNkgEgeTxPhOL9bwPInxPjRVtNiXlvWF4BqtWaeeVJGrEKZRNLHbo80RGTBgHZCqexmeFMLygT03Sh7OAi+ZsD2JUgg3RcC0XyWSU2TK1E985Sj5fGuqOYCEhAqW1/9JRPG/lJxDqfAyuisBilf36IrepMH3+V2UswDz+JYBcYNWQy+QmqrwtwL5IuyKGCw3UK0SUVazKyBTpm5zHyVhu9ucVq6l/JuZLyutyY2FgeC6r4lvKfXvuQ562bWo/j/3QBjvdMWeoVgnWS7tO6aDDJsPwdnqSj/j9jf6ORbtkvjKefv75fbsHoSP8/znGatdcojOavcVXe310hl55O7LYZpZkQ8gBfLNFTBuHXvbHChu7m80jwsgIMj/8IxpvmrQVnzS21WjdZnuRlFfsh4rRUK1qZGhWI4OeTLi/R9Ame2Zcvis946cLDtUYYuMeTCvLnPHxoRrN2a9k4="
before_install:
  - echo -n | openssl s_client -conncoverity_scanect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  apt:
    packages:
    - ant-optional
  coverity_scan:
    project:
      name: "ThJ-Stein/FreeCol-copy"
      description: "project to learn about automated CI/CD pipelines"
    notification_email: t.stouten@student.utwente.nl
    build_command_prepend: "cov-configure --java"
    build_command: "ant nightly-release"
    branch_pattern: master
script:
- ant testci
before_deploy:
- ant nightly-release
- ls -l dist/releases
